name: Retrieve version and update via semantic-release

on:
  workflow_call:
    outputs:
      version:
        description: "The new artifact version"
        value: ${{ jobs.get-version.outputs.version }}
    secrets:
      GH_TOKEN:
        description: 'A token passed from the caller workflow'
        required: true
jobs:
  get-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
    outputs:
      version: ${{ steps.store-version.outputs.versionout }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
#          persist-credentials: false
      - uses: codfish/semantic-release-action@v2
        with:
          additional_packages: |
            ['@semantic-release/changelog']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: get current version tag
        id: get-version
        run: |
          echo "$RELEASE_VERSION"
          echo "::set-output name=version::$RELEASE_VERSION"
