name: Compile the Helm Chart and Publish

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: "Version to bump to"
    secrets:
      GH_TOKEN:
        description: 'A token passed from the caller workflow'
        required: true
jobs:
  helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.6.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          charts_dir: helm
          charts_url: https://opportunitygopher.github.io/og-charts/
          owner: opportunitygopher
          repository: og-charts
          branch: gh-pages
          app_version: ${{ inputs.version }}
          chart_version: ${{ inputs.version }}



