name: Deploy the helm chart to Okteto

on:
  workflow_call:
    input:
      version:
        type: string
        required: true
        description: Version to bump to
    secrets:
      kube-config:
        description: 'Kube config file to talk to the the k8s cluster'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            helm repo add bullyrooks https://bullyrooks.github.io/helm-charts/
            helm repo update
            echo "helm upgrade message-generator bullyrooks/message-generator --install --version ${{ inputs.version }}"
            helm upgrade message-generator bullyrooks/message-generator --install --version ${{ inputs.version }}
          kubeconfig: '${{ secrets.kube-config }}'


