name: Deploy the helm chart to Okteto

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: Version to bump to
      service-name:
        type: string
        required: true
        description: Helm name
      helm-chart:
        type: string
        required: true
        description: Helm chart to deploy
    secrets:
      kube-config:
        description: 'Kube config file to talk to the the k8s cluster'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            helm repo add bullyrooks https://bullyrooks.github.io/helm-charts/
            helm repo update
            echo "helm upgrade ${{ inputs.service-name }} ${{ inputs.helm-chart }} --install --version ${{ inputs.version }}"
            helm upgrade ${{ inputs.service-name }} ${{ inputs.helm-chart }} --install --version ${{ inputs.version }}
          kubeconfig: '${{ secrets.kube-config }}'


